# Generated by Django 6.0.5 on 2026-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_unique_customer_season_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
