# Generated by Django 6.0.5 on 2026-05-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Noats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='customers.customer', verbose_name='Cliente')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='seasons.season', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'season'), name='unique_customer_season_account')],
            },
        ),
    ]
