# Generated by Django 6.0.5 on 2026-08-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
    ]
