# Generated by Django 6.0.5 on 2026-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cif', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CIF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Nº Teléfono')),
                ('adress', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
